<?php

namespace Alahaxe\SimpleTextMatcher\Tests\Classifiers;

use Alahaxe\SimpleTextMatcher\Classifiers\SVCClassifier;
use Alahaxe\SimpleTextMatcher\ModelBuilder;
use Alahaxe\SimpleTextMatcher\Stemmer;

/**
 * Class SVCClassifierTest
 *
 * @package Alahaxe\SimpleTextMatcher\Tests\Classifiers
 */
class SVCClassifierTest extends AbstractClassifierTest
{

    private static $MODEL_CACHE;

    public static function tearDownAfterClass(): void
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub

        self::$MODEL_CACHE = null;
    }


    /**
     * @inheritDoc
     */
    protected function setUp(): void
    {
        parent::setUp();

        if (self::$MODEL_CACHE !== null) {
            $this->classifier = self::$MODEL_CACHE;
            return;
        }

        self::$MODEL_CACHE = $this->classifier = new SVCClassifier();
        $this->classifier->setStemmer(new Stemmer());
        $model = require __DIR__.'/../model.php';

        $modelBuilder = new ModelBuilder();
        $this->classifier->prepareModel($modelBuilder->build($model['training'], $model['synonyms']));
    }

    /**
     * @return (mixed|string[])[]
     *
     * @psalm-return array<array-key, array{0: string, 1: string}|mixed>
     */
    public function matchProvider()
    {
        return array_merge(
            parent::matchProvider(),
            [
                // perfect match
                ['dormir a l hotel', 'dormir_dehors'],
                ['je dormir chez paul', 'dormir_amis'],
                ['je vais dormir chez paul', 'dormir_amis'],
                ['je vais acheter une voiture concessionnaire', 'acheter_voiture'],

                // with small alteration
                ['dormirais a l hotel', 'dormir_dehors'],
                ['dormirais a hotel', 'dormir_dehors'],
                ['dormirais hotel', 'dormir_dehors'],

                // with extra spaces
                ['dormirais           hotel', 'dormir_dehors'],

                // with typo
                ['je vais dormire a hotel', 'dormir_dehors'],

                // with extra text
                ['je vais dormir a hotel rue mazagran', 'dormir_dehors'],
            ]
        );
    }
}
